logging:
  file:
    name: logs/Kmarket.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  port: 8080
  servlet:
    context-path: /kmarket
spring:
  application:
    name: Kmarket
    version: ${version}
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: abc1234!
    url: jdbc:oracle:thin:@//15.165.32.191:1522/XEPDB1
    username: Kmarket
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: yd89023754@gmail.com
    password: jifeinzsrqaqrrwl
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            required: true
            enable: true
          ssl:
            trust: smtp.gmail.com

  security:
    user:
      name: user
      password: 1234
      roles: ADMIN