logging:
  file:
    name: logs/Kmarket.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  port: 8080
  servlet:
    context-path: /Kmarket
spring:
  application:
    name: Kmarket
    version: ${version}
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: TnsRnjs231123
    url: jdbc:oracle:thin:@//15.165.32.191:1522/XEPDB1
    username: sundae517
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    user:
      name: user
      password: 1234
      roles: ADMIN