logging:
  file:
    name: logs/Kmarket.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  port: 8080
  servlet:
    context-path: /kmarket
spring:
  application:
    name: Kmarket
    version: ${version}
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: abc1234!
    url: jdbc:oracle:thin:@//15.165.32.191:1522/XEPDB1
    username: Kmarket
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: yd89023754@gmail.com
    password: jifeinzsrqaqrrwl
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            required: true
            enable: true
          ssl:
            trust: smtp.gmail.com
  solapi:
    api:
      key: ${SOLAPI_KEY}
      secret: ${SOLAPI_SECRET}
      from: ${SOLAPI_FROM}

  youtube:
    api:
      api-key: ${YOUTUBE_API_KEY}
      playlist-id: "PLZGDyqLjHoLQpBJ59m1lRHGP__TCvSDF2"

  security:
    user:
      name: user
      password: 1234
      roles: ADMIN
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Naver
            authorization-grant-type: authorization_code
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

file:
  upload:
    path: C:/Kmarket/uploads/